### ISSUE TITLE
Model weights release

### ISSUE THREAD

**Issue by jacob-zietek** [google-research/language-table#9]
Hello! I think the work you've done for language-table and interactive language is really interesting, and I was wondering if you will be releasing the final weights used in the demo for [interactive language](https://interactive-language.github.io/). It would be extremely helpful for my research, as I'm interested in replicating the results presented in the demo.

Thank you for your time and great work!

**Comment by jinensetpal** [comment]
+1! Would be great to have an idea about a potential release sometime in the future. cc @ayzaan

**Comment by ayzaan** [comment]
Will work on this and keep you updated!

**Comment by jinensetpal** [comment]
Thanks!!

**Comment by jacob-zietek** [comment]
I appreciate it, thank you!

**Comment by jacob-zietek** [comment]
Hi @ayzaan! I was wondering if there were any updates on this. Thank you!

**Comment by jacob-zietek** [comment]
Great, thanks a lot!

**Comment by Ashish013** [comment]
Hey @ayzaan, thanks a lot for releasing the weights! I’m using this dataset for my research and have been stuck trying to reproduce the reported performance for a few days, so I’d really appreciate your insights.

So, when evaluating the released weights, I see a much lower performance (50 ish%) compared to the 90% accuracy reported in the paper. Is this difference because the ResNet model is kept frozen in the released weights, or is it due to the 90% accuracy being from the real-world test set rather than the benchmark you provided?

Would love to clarify this so I can adjust the code accordingly. Thanks!
